<?php

use Illuminate\Database\Seeder;

class MembersTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('members')->insert([
        	[
				'firstname'	=> 'leiding',
				'name'		=> 'leiding',
				'birthdate'	=> '01/01/1919',
				'address'	=> 'Langstraat 12-14',
				'zip'		=> '214',
				'city'		=> 'Borgerhout',
				'tel'		=> '',
				'gsm'		=> '',
				'email'		=> 'leiding@18bp.be',
				'tak'		=> 'Leiding',
				'paid'		=> 0,
				'year'		=> 0,
			],
			[
				'firstname'	=> 'Tim',
				'name'		=> 'van Dijck',
				'birthdate'	=> '25/07/1994',
				'address'	=> 'Helmstraat 82',
				'zip'		=> '2140',
				'city'		=> 'Borgerhout',
				'tel'		=> '03/236 18 92',
				'gsm'		=> '0484/97 85 67',
				'email'		=> 'tim.van.dijck@hotmail.com',
				'tak'		=> 'Leiding',
				'paid'		=> 0,
				'year'		=> 5,
			],
			[
				'firstname'	=> 'Bart',
				'name'		=> 'Devliegher',
				'birthdate'	=> '03/03/1993',
				'address'	=> 'Moeshofstraat 163',
				'zip'		=> '2170',
				'city'		=> 'Merksem',
				'tel'		=> '',
				'gsm'		=> '0475/57 76 36',
				'email'		=> 'bartdevliegher@hotmail.com',
				'tak'		=> 'Leiding',
				'paid'		=> 0,
				'year'		=> 6,
			],
			[
				'firstname'	=> 'Vincent',
				'name'		=> 'Nagels',
				'birthdate'	=> '18/01/1995',
				'address'	=> 'Laar 8',
				'zip'		=> '2140',
				'city'		=> 'Borgerhout',
				'tel'		=> '03/272 22 30',
				'gsm'		=> '0497 70 75 15',
				'email'		=> 'vincent_nagels@hotmail.com',
				'tak'		=> 'Leiding',
				'paid'		=> 0,
				'year'		=> 5,
			],
			[
				'firstname'	=> 'Amber',
				'name'		=> 'Schrauwen',
				'birthdate'	=> '02/04/1997',
				'address'	=> 'Prinshoeveweg 62',
				'zip'		=> '2180',
				'city'		=> 'Ekeren',
				'tel'		=> '03/272 11 17',
				'gsm'		=> '0479/24 16 44',
				'email'		=> 'hilde.snoopy@hotmail.com',
				'tak'		=> 'Leiding',
				'paid'		=> 0,
				'year'		=> 3,
			],
			[
				'firstname'	=> 'Bjorn',
				'name'		=> 'De Vleeschouwer',
				'birthdate'	=> '05/11/1996',
				'address'	=> 'Zwarteleeuwstraat 1',
				'zip'		=> '2140',
				'city'		=> 'Borgerhout',
				'tel'		=> '',
				'gsm'		=> '0499/45 51 84',
				'email'		=> 'bjorn.dv@hotmail.com',
				'tak'		=> 'Leiding',
				'paid'		=> 0,
				'year'		=> 3,
			],
			[
				'firstname'	=> 'Ward',
				'name'		=> 'Gladiné',
				'birthdate'	=> '28/12/1998',
				'address'	=> 'Kroonstraat 94',
				'zip'		=> '2140',
				'city'		=> 'Borgerhout',
				'tel'		=> '',
				'gsm'		=> '0479/91 35 02',
				'email'		=> 'augustyns.leen@kava.be',
				'tak'		=> 'Leiding',
				'paid'		=> 0,
				'year'		=> 1,
			],
			[
				'firstname'	=> 'yorrik@18bp.be',
				'name'		=> 'Shere Khan',
				'birthdate'	=> '19/08/1997',
				'address'	=> 'Mercatorstraat 68',
				'zip'		=> '2018',
				'city'		=> 'Antwerpen',
				'tel'		=> '',
				'gsm'		=> '',
				'email'		=> 'yorrik@18bp.be',
				'tak'		=> 'Leiding',
				'paid'		=> 0,
				'year'		=> 2,
			],
			[
				'firstname'	=> 'Aster',
				'name'		=> 'Vens',
				'birthdate'	=> '13/12/1997',
				'address'	=> 'Kwekerijstraat 17',
				'zip'		=> '2140',
				'city'		=> 'Borgerhout',
				'tel'		=> '03/235 39 95',
				'gsm'		=> '0470/22 38 10',
				'email'		=> 'aster.vens@hotmail.com',
				'tak'		=> 'Leiding',
				'paid'		=> 0,
				'year'		=> 2,
			],
			[
				'firstname'	=> 'Dagmar',
				'name'		=> 'Schrauwen',
				'birthdate'	=> '19/09/1998',
				'address'	=> 'Prinshoeveweg 62',
				'zip'		=> '2180',
				'city'		=> 'Ekeren',
				'tel'		=> '03/272 11 17',
				'gsm'		=> '0479/24 16 44',
				'email'		=> 'hilde.snoopy@hotmail.com',
				'tak'		=> 'Leiding',
				'paid'		=> 0,
				'year'		=> 1,
			],
			[
				'firstname'	=> 'Lena',
				'name'		=> 'Meyer',
				'birthdate'	=> '30/12/1997',
				'address'	=> 'Bleekhofstraat 115/33',
				'zip'		=> '2140',
				'city'		=> 'Borgerhout',
				'tel'		=> '03/235 63 25',
				'gsm'		=> '0485/64 48 89',
				'email'		=> 'lieve.meyer@skynet.be',
				'tak'		=> 'Leiding',
				'paid'		=> 0,
				'year'		=> 1,
			],
			[
				'firstname'	=> 'Jannes',
				'name'		=> 'Vens',
				'birthdate'	=> '13/12/1994',
				'address'	=> 'Kwekerijstraat 17',
				'zip'		=> '2140',
				'city'		=> 'Borgerhout',
				'tel'		=> '03/235 39 95',
				'gsm'		=> '0498/40 76 01',
				'email'		=> 'jannes.vens@hotmail.com',
				'tak'		=> 'Leiding',
				'paid'		=> 0,
				'year'		=> 5,
			],
			[
				'firstname'	=> 'Yerco',
				'name'		=> 'Gommers',
				'birthdate'	=> '28/03/1996',
				'address'	=> 'Wetstraat 67',
				'zip'		=> '2140',
				'city'		=> 'Borgerhout',
				'tel'		=> '',
				'gsm'		=> '0489/32 88 75',
				'email'		=> 'yercogommers@hotmail.com',
				'tak'		=> 'Leiding',
				'paid'		=> 0,
				'year'		=> 2,
			],
			[
				'firstname'	=> 'Shana',
				'name'		=> 'De Ridder',
				'birthdate'	=> '05/07/1995',
				'address'	=> 'Wittestraat 31/1',
				'zip'		=> '2020',
				'city'		=> 'Antwerpen',
				'tel'		=> '',
				'gsm'		=> '0485/17 92 86',
				'email'		=> 'shana_de_ridder@hotmail.com',
				'tak'		=> 'Leiding',
				'paid'		=> 0,
				'year'		=> 4,
			],
        ]);
    }
}
